a=int(input("Введите число а: "))
b=int(input("Введите число b: "))
abs_a = abs(a)
abs_b = abs(b)
print("Сумма модулей: ", abs_a + abs_b)
print("Разность модулей: ", abs(abs_a - abs_b))
print("Произведение модулей: ", abs_a * abs_b)
print("Частное модулей: ", abs_a / abs_b)
