x1 = float(input("Введите x1: "))
y1 = float(input("Введите y1: "))
x2 = float(input("Введите x2: "))
y2 = float(input("Введите y2: "))
a = abs(x1 - x2)
b = abs(y1 - y2)
p = 2 * (a + b)
s = a * b
print("Периметр прямоугольника:", p)
print("Площадь прямоугольника:", s)
